In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
import seaborn as sns

In [2]:
user=pd.read_csv("users.csv")
user["user_id"]=user["_id"]
del(user["_id"])

In [3]:
post=pd.read_csv("posts.csv")
post

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence|Machine Learning|Infor...,blog
2,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
3,5d7d405e5720533e15c3b1f3,Lord Shiva,Drawings,artwork
4,5d80dfbc6c53455f896e600e,How Competition law evolved?,Competition Laws,blog
...,...,...,...,...
488,5ed3791976027d35905ccab6,CI/CD using GitHub Actions,Computer Technology|Information Technology,blog
489,5ed3820f76027d35905ccac8,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog
490,5ed3ef4cbd514d602c1530f2,Recommendation Engine,NaN,project
491,5ed415c6bd514d602c15312d,Face Recognition using Transfer Learning.,Science; Technology,skill
492,5ed4cbadbd514d602c1531a6,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology|Computer Application|Infor...,blog

In [4]:
post["post_id"]=post["_id"]

del(post["_id"])

In [5]:
post

,title,category,post_type,post_id
0,hello there,Plant Biotechnology,blog,5d62abaa65218653a132c956
1,Ml and AI,Artificial Intelligence|Machine Learning|Infor...,blog,5d6d39567fa40e1417a4931c
2,What is an Operating System ?,Operating Systems,blog,5d7d23315720533e15c3b1ee
3,Lord Shiva,Drawings,artwork,5d7d405e5720533e15c3b1f3
4,How Competition law evolved?,Competition Laws,blog,5d80dfbc6c53455f896e600e
...,...,...,...,...
488,CI/CD using GitHub Actions,Computer Technology|Information Technology,blog,5ed3791976027d35905ccab6
489,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,5ed3820f76027d35905ccac8
490,Recommendation Engine,NaN,project,5ed3ef4cbd514d602c1530f2
491,Face Recognition using Transfer Learning.,Science; Technology,skill,5ed415c6bd514d602c15312d
492,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology|Computer Application|Infor...,blog,5ed4cbadbd514d602c1531a6

In [6]:
view=pd.read_csv("views.csv")
view

,user_id,post_id,timestamp
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z
1,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z
2,5ed0defa76027d35905cc2de,5eac305f10426255a7aa9dd3,2020-06-01T08:12:42.682Z
3,5ed0defa76027d35905cc2de,5ed1ff0276027d35905cc60d,2020-06-01T08:10:23.880Z
4,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z
...,...,...,...
1444,5d60098a653a331687083238,5e7a60edcfc8b713f5ac7d82,2020-03-26T19:03:55.284Z
1445,5d60098a653a331687083238,5e7a629ccfc8b713f5ac7d84,2020-03-26T19:01:42.384Z
1446,5d60098a653a331687083238,5e7b1e65cfc8b713f5ac7d90,2020-03-26T19:00:25.693Z
1447,5d60098a653a331687083238,5e7cc074cfc8b713f5ac7db0,2020-03-26T18:49:14.721Z
1448,5d60098a653a331687083238,5e1029f22a37d20505da2a79,2020-03-26T18:25:45.637Z

In [7]:
merge=pd.merge(user, view, on=['user_id'])
merge.head()

,name,gender,academics,user_id,post_id,timestamp
0,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed3820f76027d35905ccac8,2020-05-31T18:01:54.308Z
1,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed1ff0276027d35905cc60d,2020-05-31T08:21:29.911Z
2,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ecf96e876027d35905cbf46,2020-05-29T19:13:27.566Z
3,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ecfa0ca76027d35905cbf57,2020-05-29T19:10:50.010Z
4,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed0e20776027d35905cc2fe,2020-05-29T19:10:23.887Z

In [8]:
merge_final=pd.merge(merge, post, on=['post_id'])
merge_final.head()
data=merge_final
data.index.name='index'
#merge_final.to_csv("merge_final.csv")
data

,name,gender,academics,user_id,post_id,timestamp,title,category,post_type
index,,,,,,,,,
0,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed3820f76027d35905ccac8,2020-05-31T18:01:54.308Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog
1,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed3820f76027d35905ccac8,2020-05-31T20:40:18.693Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog
2,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog
3,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed3820f76027d35905ccac8,2020-05-31T10:08:37.079Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog
4,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed1ff0276027d35905cc60d,2020-05-31T08:21:29.911Z,AWS services and how to launch OS on AWS Cloud,Computer Technology|Cloud Computing,blog
...,...,...,...,...,...,...,...,...,...
1442,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5de179d80eb5e25a8a07f079,2020-05-30T10:26:47.432Z,Navigation system using BFS DFS algorithms,NaN,project
1443,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed175f476027d35905cc562,2020-05-29T20:53:54.008Z,GAN's Introduction,NaN,project
1444,ashish,male,graduate,5ecf6e6576027d35905cbeec,5ed0007a76027d35905cc0ea,2020-05-29T09:00:06.934Z,A solar-powered microbrewery has design-led en...,Artistic design,artwork
1445,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed23d4276027d35905cc798,2020-06-01T08:07:22.659Z,Energy.,Calligraphy|Typography|Pen and ink,artwork
1446,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology|Computer Application|Infor...,blog

In [9]:
data["category"].nunique()

231

In [10]:
data["post_type"].unique()

array(['blog', 'artwork', 'skill', 'project'], dtype=object)

In [11]:
data.groupby("category")["title"].count()#.sort_values(ascending=False).head(10)

category
2D Composition|Watercolours|Painting                                                       3
Accounting|Financial Accounting                                                            2
Accounting|Fundamental Of Accounting                                                       3
Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices     2
Archeology|Human Prehistory                                                                4
                                                                                          ..
Visual Arts|Graphic Design|Artistic design|Graphic|Illustration                           10
Visual Arts|Photography                                                                    9
Watercolours                                                                               3
Zoology|Ecology                                                                            1
Zoology|Environmental Biology                                                              2
Name: title, Length: 231, dtype: int64

In [12]:
data.groupby("post_type")["title"].count().sort_values(ascending=False).head(10)

post_type
artwork    752
blog       472
skill      136
project     87
Name: title, dtype: int64

In [13]:
data.groupby("category")["title"].groups

{'2D Composition|Watercolours|Painting': Int64Index([947, 948, 949], dtype='int64', name='index'),
 'Accounting|Financial Accounting': Int64Index([615, 616], dtype='int64', name='index'),
 'Accounting|Fundamental Of Accounting': Int64Index([828, 829, 1345], dtype='int64', name='index'),
 'Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices': Int64Index([710, 711], dtype='int64', name='index'),
 'Archeology|Human Prehistory': Int64Index([669, 670, 671, 672], dtype='int64', name='index'),
 'Architecture': Int64Index([514], dtype='int64', name='index'),
 'Art': Int64Index([ 190,  191,  192,  193,  194,  195,  906,  907,  908,  909,  910,
             1102, 1103, 1104, 1105, 1106, 1107, 1108],
            dtype='int64', name='index'),
 'Art; Science': Int64Index([216, 217, 218, 219, 220, 221, 222, 223], dtype='int64', name='index'),
 'Artificial Intelligence|Machine Learning|Information Technology': Int64Index([705], dtype='int64', name='index'),
 'Artistic design': Int64Index([1444], dtype='int64', name='index'),
 'Artistic design|Logo Design|Graphic|Illustration': Int64Index([894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905], dtype='int64', name='index'),
 'Auditing|Audit Evidence': Int64Index([1353], dtype='int64', name='index'),
 'Auditing|Audit Remark': Int64Index([1358], dtype='int64', name='index'),
 'Auditing|Cost Audit': Int64Index([1359], dtype='int64', name='index'),
 'Auditing|Internal Audit': Int64Index([1352], dtype='int64', name='index'),
 'Auditing|Internal Financial Control': Int64Index([1351], dtype='int64', name='index'),
 'Auditing|Secratarial Audit': Int64Index([1356], dtype='int64', name='index'),
 'Auditing|Statuary Audit': Int64Index([1203], dtype='int64', name='index'),
 'Banking|Banking Companies': Int64Index([1200, 1201, 1202], dtype='int64', name='index'),
 'Banking|Banking Technology': Int64Index([1357], dtype='int64', name='index'),
 'Biotechnology|Animal Biotechnology': Int64Index([328, 329], dtype='int64', name='index'),
 'Biotechnology|Environmental Biotechnology': Int64Index([538], dtype='int64', name='index'),
 'Biotechnology|Genetic Engineering': Int64Index([1173], dtype='int64', name='index'),
 'Biotechnology|Molecular Biology': Int64Index([1169, 1170, 1171], dtype='int64', name='index'),
 'Biotechnology|Plant Biotechnology': Int64Index([822, 823, 824, 825, 826], dtype='int64', name='index'),
 'Business': Int64Index([436, 437, 438, 439, 440, 441, 442], dtype='int64', name='index'),
 'Business|Bio-entrepreneurship': Int64Index([1021, 1022], dtype='int64', name='index'),
 'Business|Business Organisation': Int64Index([699, 732, 733, 745, 746, 747], dtype='int64', name='index'),
 'Business|Business Skills': Int64Index([1327], dtype='int64', name='index'),
 'Business|Business Strategies|Business Enviorment|New Venture Planning|Foreign Business|Business Organisation': Int64Index([430, 431, 432, 433, 434], dtype='int64', name='index'),
 'Business|Business Strategies|Venture Capitalist': Int64Index([1339], dtype='int64', name='index'),
 'Business|Corporate Social Responsibilities': Int64Index([1335], dtype='int64', name='index'),
 'Business|Entreperneurship|Venture Capitalist|Business Enviorment|Start Ups|Business Planning|New Venture Planning': Int64Index([312, 313], dtype='int64', name='index'),
 'Business|Start Ups|Entreperneurship|Business Strategies|Venture Capitalist|Business Planning': Int64Index([673, 674], dtype='int64', name='index'),
 'Calligraphy': Int64Index([1320], dtype='int64', name='index'),
 'Calligraphy|Pen and ink': Int64Index([1438], dtype='int64', name='index'),
 'Calligraphy|Typography|Pen and ink': Int64Index([1431, 1439, 1445], dtype='int64', name='index'),
 'Communication|Basics of Communiaction': Int64Index([1136, 1137, 1138], dtype='int64', name='index'),
 'Competition Laws': Int64Index([860, 861, 1041, 1042, 1043, 1059, 1060, 1398, 1401], dtype='int64', name='index'),
 'Computer Technology|Artificial Intelligence': Int64Index([1058, 1414], dtype='int64', name='index'),
 'Computer Technology|Cloud Computing': Int64Index([   4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
               15,   32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
               42,   43,   44, 1175, 1176],
            dtype='int64', name='index'),
 'Computer Technology|Cloud Computing|Artificial Intelligence|Information Technology|Programming languages': Int64Index([1384], dtype='int64', name='index'),
 'Computer Technology|Computation': Int64Index([1233, 1255], dtype='int64', name='index'),
 'Computer Technology|Computation|Computer Application': Int64Index([1276], dtype='int64', name='index'),
 'Computer Technology|Computation|Computer Application|Cloud Computing': Int64Index([1416, 1417], dtype='int64', name='index'),
 'Computer Technology|Computer Application': Int64Index([675, 676, 677, 1281, 1299, 1385, 1386], dtype='int64', name='index'),
 'Computer Technology|Computer Application|Hardware|Information Technology': Int64Index([1249, 1250], dtype='int64', name='index'),
 'Computer Technology|Computer Application|Information Technology': Int64Index([   0,    1,    2,    3, 1143, 1144, 1145, 1146, 1278, 1279, 1288,
             1289, 1294, 1295, 1296, 1297, 1298, 1446],
            dtype='int64', name='index'),
 'Computer Technology|Computer Application|Operating Systems': Int64Index([1232], dtype='int64', name='index'),
 'Computer Technology|Computer Application|Programming languages|Information Technology': Int64Index([1247, 1248], dtype='int64', name='index'),
 'Computer Technology|Data Science': Int64Index([1070, 1071, 1072, 1073, 1074, 1075, 1076, 1387], dtype='int64', name='index'),
 'Computer Technology|Design and Analysis of Algorithms': Int64Index([737, 738, 739], dtype='int64', name='index'),
 'Computer Technology|Design and Analysis of Algorithms|Programming languages': Int64Index([1275], dtype='int64', name='index'),
 'Computer Technology|Design and Analysis of Algorithms|Web designing|Database Management|Artificial Intelligence': Int64Index([552, 553], dtype='int64', name='index'),
 'Computer Technology|Hardware|Information Technology': Int64Index([1286], dtype='int64', name='index'),
 'Computer Technology|Information Technology': Int64Index([1246, 1280, 1415, 1424, 1425], dtype='int64', name='index'),
 'Computer Technology|Information Technology|Computer Application': Int64Index([1238, 1239, 1291, 1292, 1293], dtype='int64', name='index'),
 'Computer Technology|Machine Learning': Int64Index([  16,   17,   18,   19,   20,   21,   22,   23,   24,   25,   53,
               54,   55,   56,   57,  113,  114,  115,  116,  117,  118,  119,
              120,  121,  122,  123,  124,  125,  126,  127,  128,  697,  698,
              734,  735,  736, 1418, 1419, 1420, 1421],
            dtype='int64', name='index'),
 'Computer Technology|Mobile Applications': Int64Index([1229, 1290], dtype='int64', name='index'),
 'Computer Technology|Operating Systems': Int64Index([1167], dtype='int64', name='index'),
 'Computer Technology|Programming languages': Int64Index([1237, 1245], dtype='int64', name='index'),
 'Computer Technology|Robotics|Data Science|Information Technology|Artificial Intelligence': Int64Index([784, 785, 786], dtype='int64', name='index'),
 'Computer Technology|Web designing|Artificial Intelligence|Computer Application|Machine Learning|Frontend Development': Int64Index([984, 985], dtype='int64', name='index'),
 'Conceptual': Int64Index([842, 1090], dtype='int64', name='index'),
 'Conceptual|Graphic Design': Int64Index([848, 849], dtype='int64', name='index'),
 'Craft work': Int64Index([597, 598, 599, 600], dtype='int64', name='index'),
 'Craft|Artistic design': Int64Index([979, 980, 981, 982], dtype='int64', name='index'),
 'Craft|Drawings|Conceptual|2D Composition': Int64Index([926, 927, 928, 929, 930, 931], dtype='int64', name='index'),
 'Craft|Mixed Media|Conceptual|Mosaic painting|2D Composition': Int64Index([335, 336, 337, 338, 339, 340], dtype='int64', name='index'),
 'Digital Marketing': Int64Index([811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821], dtype='int64', name='index'),
 'Drawing': Int64Index([890, 891, 892, 893, 1035, 1036, 1260, 1261, 1262], dtype='int64', name='index'),
 'Drawings': Int64Index([ 208,  209,  210,  211,  212,  213,  214,  215,  245,  246,
             ...
             1244, 1251, 1252, 1266, 1267, 1268, 1316, 1317, 1318, 1395],
            dtype='int64', name='index', length=149),
 'Drawings|Artistic design': Int64Index([1263], dtype='int64', name='index'),
 'Drawings|Artistic design|Illustration': Int64Index([1274], dtype='int64', name='index'),
 'Drawings|Calligraphy': Int64Index([827, 1319], dtype='int64', name='index'),
 'Drawings|Fashion Design|Illustration|Watercolours': Int64Index([ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91, 169,
             170, 171, 172, 173, 174, 175, 176, 177, 178],
            dtype='int64', name='index'),
 'Drawings|Fashion Design|Mixed Media|Conceptual|Illustration|Pen and ink|Watercolours': Int64Index([104, 105, 106, 107, 108, 109, 110, 111, 112], dtype='int64', name='index'),
 'Drawings|Painting': Int64Index([1192, 1193, 1194, 1323], dtype='int64', name='index'),
 'Drawings|Painting|Visual Arts|Artistic design|Watercolours|Acrylics': Int64Index([787, 788, 789, 790, 791, 792, 793, 794, 795], dtype='int64', name='index'),
 'Drawings|Painting|Visual Arts|Graphic Design|Prints|Illustration': Int64Index([314], dtype='int64', name='index'),
 'Drawings|Painting|Watercolours': Int64Index([1088, 1089], dtype='int64', name='index'),
 'Drawings|Visual Arts|Painting|Graphic Design|Artistic design|Illustration': Int64Index([1228], dtype='int64', name='index'),
 'Drawings|Watercolours': Int64Index([1350], dtype='int64', name='index'),
 'E Commerce|E Transactions': Int64Index([1271, 1272, 1285], dtype='int64', name='index'),
 'E Commerce|Other Online Platforms': Int64Index([1264], dtype='int64', name='index'),
 'E Commerce|Shopping Platform|Other Online Platforms': Int64Index([1273], dtype='int64', name='index'),
 'E Commerce|Shopping Platform|Other Online Platforms|Digital India': Int64Index([1020], dtype='int64', name='index'),
 'Eco System': Int64Index([1172], dtype='int64', name='index'),
 'Economic Policies': Int64Index([1199], dtype='int64', name='index'),
 'Economics|Economic Policies|Break even Point|Foreign Economy': Int64Index([1009, 1010, 1011], dtype='int64', name='index'),
 'Economics|Economics Sociology': Int64Index([1360], dtype='int64', name='index'),
 'Economics|Indian Economy': Int64Index([582, 583], dtype='int64', name='index'),
 'Economics|Revenue Concept': Int64Index([592, 593, 594, 1209, 1210], dtype='int64', name='index'),
 'Education': Int64Index([764, 765], dtype='int64', name='index'),
 'Electronics & electrical Technology|Electrical Machines': Int64Index([1328], dtype='int64', name='index'),
 'Empowerment': Int64Index([1383], dtype='int64', name='index'),
 'Environment Studies|Pollution|Environmental Biology': Int64Index([1008], dtype='int64', name='index'),
 'Fashion Desigining|Fashion Illustration|Pattern Cutting|Fashion Communication': Int64Index([350, 351, 352, 353, 354, 355, 356, 357], dtype='int64', name='index'),
 'Fashion Desigining|Fashion Textile|Fashion Manufacturing|Fashion Techniques|Garment Production|Garment Technology': Int64Index([807, 808, 809, 810], dtype='int64', name='index'),
 'Fashion Desigining|Pattern & Culture|Fashion Textile|Fashion Trends': Int64Index([269, 270, 271, 272, 273, 274, 275, 276], dtype='int64', name='index'),
 'Fashion Desigining|Pattern & Culture|Fashion Trends|Fashion Portfoilio': Int64Index([921, 922, 923, 924, 925], dtype='int64', name='index'),
 'Fashion Design': Int64Index([956, 957, 958], dtype='int64', name='index'),
 'Fashion Design|Ceramics|Artistic design': Int64Index([959, 960], dtype='int64', name='index'),
 'Fashion Design|Illustration|Conceptual|Watercolours|Pen and ink': Int64Index([92, 93, 94, 95, 96, 97, 98, 99, 100, 101], dtype='int64', name='index'),
 'Fashion Design|Illustration|Watercolours': Int64Index([62, 63, 64, 65, 66, 67, 68], dtype='int64', name='index'),
 'Fashion Design|Illustration|Watercolours|Drawings': Int64Index([69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], dtype='int64', name='index'),
 'Fashion Design|Visual Arts|Conceptual|Artistic design': Int64Index([932, 933, 934, 935, 936, 937], dtype='int64', name='index'),
 'Fashion Design|Visual Arts|Graphic Design|Artistic design|Graphic|Illustration': Int64Index([961, 962, 963], dtype='int64', name='index'),
 'Finance|Financial Analysis': Int64Index([1341, 1342], dtype='int64', name='index'),
 'Fine Arts|Painting': Int64Index([401, 402, 403, 404, 405, 406], dtype='int64', name='index'),
 'Geography|Indian Geography': Int64Index([532, 533, 534, 535, 536, 537, 1388, 1389, 1390], dtype='int64', name='index'),
 'Geography|Physical Geography': Int64Index([632, 633, 634, 750, 751, 1346, 1347, 1348], dtype='int64', name='index'),
 'Graphic Design': Int64Index([1048], dtype='int64', name='index'),
 'Graphic Design|Visual Arts': Int64Index([768, 769, 770, 771], dtype='int64', name='index'),
 'Graphic Design|Visual Arts|Illustration|Graphic': Int64Index([1324], dtype='int64', name='index'),
 'Graphics|Articulation|Computer Creation': Int64Index([685, 686, 687, 688], dtype='int64', name='index'),
 'Graphics|Computer Creation': Int64Index([1265, 1277], dtype='int64', name='index'),
 'Graphic|Graphic Design': Int64Index([1408], dtype='int64', name='index'),
 'HR Management': Int64Index([1329], dtype='int64', name='index'),
 'History|Indian History': Int64Index([1023, 1024, 1025, 1409], dtype='int64', name='index'),
 'Human Resources|HR Management': Int64Index([1331], dtype='int64', name='index'),
 'Human Resources|Performance In Organization': Int64Index([783], dtype='int64', name='index'),
 'Human Resources|Performance In Organization|Organizational Behaviour|HR Management': Int64Index([1404], dtype='int64', name='index'),
 'Human Rights|Fundamental Rights': Int64Index([689, 690, 691, 692], dtype='int64', name='index'),
 'Human Rights|Fundamental Rights|Protection & Enforcement': Int64Index([435], dtype='int64', name='index'),
 'Human Rights|Rights and Duties': Int64Index([1211, 1212, 1213, 1214, 1215], dtype='int64', name='index'),
 'Inorganic Chemistry': Int64Index([1177], dtype='int64', name='index'),
 'Learning': Int64Index([ 143,  144,  145,  146,  147,  148,  149, 1061, 1062, 1063, 1064,
             1065, 1066, 1067, 1068, 1069],
            dtype='int64', name='index'),
 'Legal Studies|Alternate Dispute Resolution|International Treaties|International Agreement': Int64Index([1016, 1017, 1018], dtype='int64', name='index'),
 'Legal Studies|Company Law|Legal System|Banking Law': Int64Index([983], dtype='int64', name='index'),
 'Legal Studies|Income Tax Laws': Int64Index([1026, 1027], dtype='int64', name='index'),
 'Legal Studies|Labor Law': Int64Index([1225, 1226, 1227], dtype='int64', name='index'),
 'Legal Studies|Legal System': Int64Index([1204, 1205], dtype='int64', name='index'),
 'Legal Studies|Legal System|Legal Tradition|Nationality Law|Government Law': Int64Index([419, 420], dtype='int64', name='index'),
 'Literature|Movements in Literature': Int64Index([556], dtype='int64', name='index'),
 'Literature|Stories': Int64Index([595, 596, 1391], dtype='int64', name='index'),
 'Literature|Stories|Fictions|Movements in Literature': Int64Index([26, 27], dtype='int64', name='index'),
 'Management|Business Management': Int64Index([621, 622, 623], dtype='int64', name='index'),
 'Management|Business Management|Technology Mangement|Managerial Activity|Creative And Lateral Management': Int64Index([415, 416, 417, 418], dtype='int64', name='index'),
 'Management|Team Mangememnt': Int64Index([1336], dtype='int64', name='index'),
 'Marketing|Advertising': Int64Index([1019, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1399], dtype='int64', name='index'),
 'Marketing|Marketing Management': Int64Index([728, 729, 730, 731], dtype='int64', name='index'),
 'Marketing|Principles Of Marketing|International Marketing|Promotion And Distribution Decisions': Int64Index([364, 365, 366], dtype='int64', name='index'),
 'Marketing|Principles Of Marketing|Marketing Research Methadology|Marketing Management|International Marketing': Int64Index([443, 444, 445, 446], dtype='int64', name='index'),
 'Marketing|Promotion And Distribution Decisions': Int64Index([1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368], dtype='int64', name='index'),
 'Mass Media|Indian Government': Int64Index([589, 590, 591, 712, 713, 714, 715, 774, 775, 776, 777, 1044, 1045,
             1046, 1174],
            dtype='int64', name='index'),
 'Mass Media|International Relations': Int64Index([832], dtype='int64', name='index'),
 'Mass Media|Media And Society': Int64Index([1440], dtype='int64', name='index'),
 'Mass Media|Videography': Int64Index([799, 800, 801, 802, 803, 804], dtype='int64', name='index'),
 'Mathematics|Linear Algebra': Int64Index([1330], dtype='int64', name='index'),
 'Mixed Media': Int64Index([28, 424, 425, 426, 427, 428, 429, 1377, 1378, 1379, 1380, 1381,
             1382],
            dtype='int64', name='index'),
 'Mixed Media|Calligraphy|Pen and ink': Int64Index([1436], dtype='int64', name='index'),
 'Mixed Media|Conceptual': Int64Index([1396], dtype='int64', name='index'),
 'Music': Int64Index([367, 368, 369, 370], dtype='int64', name='index'),
 'Operating Systems': Int64Index([1269, 1270], dtype='int64', name='index'),
 'Painting': Int64Index([ 179,  180,  181,  182,  183,  184,  185,  186,  187,  188,  189,
              196,  197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
              207,  298,  299,  300,  301,  302,  303,  304,  305,  306,  307,
              308,  309,  310,  421,  447,  448,  465,  466,  467,  471,  472,
              473,  474,  493,  494,  495,  496,  520,  521,  522,  523,  527,
              528,  529,  530,  531,  542,  543,  544,  545,  546,  547,  919,
              920,  998,  999, 1000, 1125, 1126, 1259, 1349, 1392],
            dtype='int64', name='index'),
 'Painting|Craft|Artistic design': Int64Index([964, 965, 966, 967], dtype='int64', name='index'),
 'Painting|Craft|Mixed Media|2D Composition': Int64Index([971, 972, 973, 974], dtype='int64', name='index'),
 'Painting|Visual Arts|Craft|Conceptual': Int64Index([371, 372, 373, 374, 375], dtype='int64', name='index'),
 'Painting|Watercolours|2D Composition': Int64Index([940, 941, 942, 943, 944, 945, 946], dtype='int64', name='index'),
 'Pen and ink': Int64Index([235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 837, 838, 1253], dtype='int64', name='index'),
 'Philosophy|Applied Ethics': Int64Index([311], dtype='int64', name='index'),
 'Philosophy|Logic': Int64Index([638, 639, 640, 641, 642, 643, 781], dtype='int64', name='index'),
 'Philosophy|Public Philosophy': Int64Index([833, 834, 835], dtype='int64', name='index'),
 'Photography': Int64Index([  58,   59,   60,   61,  102,  103,  129,  130,  131,  132,
             ...
             1325, 1326, 1332, 1334, 1397, 1402, 1405, 1406, 1407, 1410],
            dtype='int64', name='index', length=241),
 'Photography|Architecture': Int64Index([569, 570, 1127, 1128, 1300, 1301, 1303], dtype='int64', name='index'),
 'Photography|Architecture|Illustration': Int64Index([568], dtype='int64', name='index'),
 'Photography|Architecture|Painting': Int64Index([555], dtype='int64', name='index'),
 'Photography|Architecture|Visual Arts|Graphic Design': Int64Index([1129, 1130, 1131, 1132], dtype='int64', name='index'),
 'Photography|Architecture|Visual Arts|Graphic Design|Artistic design|Graphic|Logo Design': Int64Index([150, 151, 152, 153, 154, 155, 156], dtype='int64', name='index'),
 'Photography|Conceptual': Int64Index([566, 567, 575, 576], dtype='int64', name='index'),
 'Photography|Conceptual|Illustration': Int64Index([519], dtype='int64', name='index'),

In [14]:
df=(data[data['title']=='आमची मुंबाई !!!'].index.values)
df[0]

1023

# split the category

In [15]:
data[["main_cate","cate_1","cate_2","cate_3","cate_4","cate_5","cate_6"]]=data.category.str.split("|" , expand=True)
data

,name,gender,academics,user_id,post_id,timestamp,title,category,post_type,main_cate,cate_1,cate_2,cate_3,cate_4,cate_5,cate_6
index,,,,,,,,,,,,,,,,
0,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed3820f76027d35905ccac8,2020-05-31T18:01:54.308Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
1,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed3820f76027d35905ccac8,2020-05-31T20:40:18.693Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
2,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
3,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed3820f76027d35905ccac8,2020-05-31T10:08:37.079Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
4,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed1ff0276027d35905cc60d,2020-05-31T08:21:29.911Z,AWS services and how to launch OS on AWS Cloud,Computer Technology|Cloud Computing,blog,Computer Technology,Cloud Computing,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5de179d80eb5e25a8a07f079,2020-05-30T10:26:47.432Z,Navigation system using BFS DFS algorithms,NaN,project,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed175f476027d35905cc562,2020-05-29T20:53:54.008Z,GAN's Introduction,NaN,project,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1444,ashish,male,graduate,5ecf6e6576027d35905cbeec,5ed0007a76027d35905cc0ea,2020-05-29T09:00:06.934Z,A solar-powered microbrewery has design-led en...,Artistic design,artwork,Artistic design,None,None,None,None,None,None
1445,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed23d4276027d35905cc798,2020-06-01T08:07:22.659Z,Energy.,Calligraphy|Typography|Pen and ink,artwork,Calligraphy,Typography,Pen and ink,None,None,None,None
1446,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None

#data.fillna(0, inplace=True)
data

In [16]:
x=data.groupby(["main_cate","cate_1","cate_2",'cate_3',"cate_4","cate_5"])["title"].count().sort_values(ascending=False).head(20)

In [17]:
x.head()

main_cate    cate_1               cate_2                      cate_3                cate_4                      cate_5
Drawings     Painting             Visual Arts                 Artistic design       Watercolours                Acrylics                 9
             Fashion Design       Mixed Media                 Conceptual            Illustration                Pen and ink              9
Photography  Architecture         Visual Arts                 Graphic Design        Artistic design             Graphic                  7
Business     Business Strategies  Business Enviorment         New Venture Planning  Foreign Business            Business Organisation    5
Physics      Quantum Mecahnics    Industrial Instrumentation  Atomic Physics        Nuclear & Particle Physics  Energy Physics           4
Name: title, dtype: int64

In [18]:
cate_group=data.groupby(["main_cate","cate_1","cate_2",'cate_3',"cate_4","cate_5"]).groups
cate_group=cate_group.values()
cate_group=list(cate_group)
cate_group

[Int64Index([   0,    1,    2,    3, 1143, 1144, 1145, 1146, 1278, 1279, 1288,
             1289, 1294, 1295, 1296, 1297, 1298, 1446],
            dtype='int64', name='index'),
 Int64Index([   4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
               15,   32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
               42,   43,   44, 1175, 1176],
            dtype='int64', name='index'),
 Int64Index([  16,   17,   18,   19,   20,   21,   22,   23,   24,   25,   53,
               54,   55,   56,   57,  113,  114,  115,  116,  117,  118,  119,
              120,  121,  122,  123,  124,  125,  126,  127,  128,  697,  698,
              734,  735,  736, 1418, 1419, 1420, 1421],
            dtype='int64', name='index'),
 Int64Index([26, 27], dtype='int64', name='index'),
 Int64Index([28, 424, 425, 426, 427, 428, 429, 1377, 1378, 1379, 1380, 1381,
             1382],
            dtype='int64', name='index'),
 Int64Index([29, 30, 31, 1218, 1219], dtype='int64', name='index'),
 Int64Index([45, 46, 47, 48, 49, 50, 51, 52, 1422, 1423], dtype='int64', name='index'),
 Int64Index([  58,   59,   60,   61,  102,  103,  129,  130,  131,  132,
             ...
             1325, 1326, 1332, 1334, 1397, 1402, 1405, 1406, 1407, 1410],
            dtype='int64', name='index', length=241),
 Int64Index([62, 63, 64, 65, 66, 67, 68], dtype='int64', name='index'),
 Int64Index([69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], dtype='int64', name='index'),
 Int64Index([ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91, 169,
             170, 171, 172, 173, 174, 175, 176, 177, 178],
            dtype='int64', name='index'),
 Int64Index([92, 93, 94, 95, 96, 97, 98, 99, 100, 101], dtype='int64', name='index'),
 Int64Index([104, 105, 106, 107, 108, 109, 110, 111, 112], dtype='int64', name='index'),
 Int64Index([ 143,  144,  145,  146,  147,  148,  149, 1061, 1062, 1063, 1064,
             1065, 1066, 1067, 1068, 1069],
            dtype='int64', name='index'),
 Int64Index([150, 151, 152, 153, 154, 155, 156], dtype='int64', name='index'),
 Int64Index([157, 158], dtype='int64', name='index'),
 Int64Index([ 159,  160,  161,  162,  163,  164,  165,  166,  167,  168,  277,
              278,  279,  390,  391,  392,  393,  394,  486,  487,  488,  489,
              490,  491,  492,  617,  618,  619,  620,  678,  679,  680,  681,
              682,  683,  684,  850,  851,  852,  853,  854,  855,  856,  857,
              858,  859, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1077, 1078,
             1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1152, 1153,
             1154, 1155, 1156, 1157, 1165, 1166, 1234, 1235, 1236, 1240, 1254,
             1256, 1257, 1258, 1282, 1283, 1284, 1287, 1333, 1428, 1442, 1443],
            dtype='int64', name='index'),
 Int64Index([ 179,  180,  181,  182,  183,  184,  185,  186,  187,  188,  189,
              196,  197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
              207,  298,  299,  300,  301,  302,  303,  304,  305,  306,  307,
              308,  309,  310,  421,  447,  448,  465,  466,  467,  471,  472,
              473,  474,  493,  494,  495,  496,  520,  521,  522,  523,  527,
              528,  529,  530,  531,  542,  543,  544,  545,  546,  547,  919,
              920,  998,  999, 1000, 1125, 1126, 1259, 1349, 1392],
            dtype='int64', name='index'),
 Int64Index([ 190,  191,  192,  193,  194,  195,  906,  907,  908,  909,  910,
             1102, 1103, 1104, 1105, 1106, 1107, 1108],
            dtype='int64', name='index'),
 Int64Index([ 208,  209,  210,  211,  212,  213,  214,  215,  245,  246,
             ...
             1244, 1251, 1252, 1266, 1267, 1268, 1316, 1317, 1318, 1395],
            dtype='int64', name='index', length=149),
 Int64Index([216, 217, 218, 219, 220, 221, 222, 223], dtype='int64', name='index'),
 Int64Index([224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234], dtype='int64', name='index'),
 Int64Index([235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 837, 838, 1253], dtype='int64', name='index'),
 Int64Index([258, 259, 260], dtype='int64', name='index'),
 Int64Index([268], dtype='int64', name='index'),
 Int64Index([269, 270, 271, 272, 273, 274, 275, 276], dtype='int64', name='index'),
 Int64Index([311], dtype='int64', name='index'),
 Int64Index([312, 313], dtype='int64', name='index'),
 Int64Index([314], dtype='int64', name='index'),
 Int64Index([328, 329], dtype='int64', name='index'),
 Int64Index([335, 336, 337, 338, 339, 340], dtype='int64', name='index'),
 Int64Index([341, 342, 343, 344, 345, 346, 347, 348, 349], dtype='int64', name='index'),
 Int64Index([350, 351, 352, 353, 354, 355, 356, 357], dtype='int64', name='index'),
 Int64Index([364, 365, 366], dtype='int64', name='index'),
 Int64Index([367, 368, 369, 370], dtype='int64', name='index'),
 Int64Index([371, 372, 373, 374, 375], dtype='int64', name='index'),
 Int64Index([398, 399], dtype='int64', name='index'),
 Int64Index([400], dtype='int64', name='index'),
 Int64Index([401, 402, 403, 404, 405, 406], dtype='int64', name='index'),
 Int64Index([411, 412, 413, 414, 1413], dtype='int64', name='index'),
 Int64Index([415, 416, 417, 418], dtype='int64', name='index'),
 Int64Index([419, 420], dtype='int64', name='index'),
 Int64Index([430, 431, 432, 433, 434], dtype='int64', name='index'),
 Int64Index([435], dtype='int64', name='index'),
 Int64Index([436, 437, 438, 439, 440, 441, 442], dtype='int64', name='index'),
 Int64Index([443, 444, 445, 446], dtype='int64', name='index'),
 Int64Index([449, 450, 451], dtype='int64', name='index'),
 Int64Index([453, 454, 455, 456, 457], dtype='int64', name='index'),
 Int64Index([500, 501, 502, 503, 504, 505, 506, 507, 508], dtype='int64', name='index'),
 Int64Index([514], dtype='int64', name='index'),
 Int64Index([519], dtype='int64', name='index'),
 Int64Index([532, 533, 534, 535, 536, 537, 1388, 1389, 1390], dtype='int64', name='index'),
 Int64Index([538], dtype='int64', name='index'),
 Int64Index([548, 549, 550, 551], dtype='int64', name='index'),
 Int64Index([552, 553], dtype='int64', name='index'),
 Int64Index([555], dtype='int64', name='index'),
 Int64Index([556], dtype='int64', name='index'),
 Int64Index([566, 567, 575, 576], dtype='int64', name='index'),
 Int64Index([568], dtype='int64', name='index'),
 Int64Index([569, 570, 1127, 1128, 1300, 1301, 1303], dtype='int64', name='index'),
 Int64Index([574], dtype='int64', name='index'),
 Int64Index([578, 579, 580, 581], dtype='int64', name='index'),
 Int64Index([582, 583], dtype='int64', name='index'),
 Int64Index([584, 585, 586], dtype='int64', name='index'),
 Int64Index([587, 588], dtype='int64', name='index'),
 Int64Index([589, 590, 591, 712, 713, 714, 715, 774, 775, 776, 777, 1044, 1045,
             1046, 1174],
            dtype='int64', name='index'),
 Int64Index([592, 593, 594, 1209, 1210], dtype='int64', name='index'),
 Int64Index([595, 596, 1391], dtype='int64', name='index'),
 Int64Index([597, 598, 599, 600], dtype='int64', name='index'),
 Int64Index([601, 602, 603, 604], dtype='int64', name='index'),
 Int64Index([615, 616], dtype='int64', name='index'),
 Int64Index([621, 622, 623], dtype='int64', name='index'),
 Int64Index([632, 633, 634, 750, 751, 1346, 1347, 1348], dtype='int64', name='index'),
 Int64Index([635, 636, 637], dtype='int64', name='index'),
 Int64Index([638, 639, 640, 641, 642, 643, 781], dtype='int64', name='index'),
 Int64Index([669, 670, 671, 672], dtype='int64', name='index'),
 Int64Index([673, 674], dtype='int64', name='index'),
 Int64Index([675, 676, 677, 1281, 1299, 1385, 1386], dtype='int64', name='index'),
 Int64Index([685, 686, 687, 688], dtype='int64', name='index'),
 Int64Index([689, 690, 691, 692], dtype='int64', name='index'),
 Int64Index([693, 694], dtype='int64', name='index'),
 Int64Index([699, 732, 733, 745, 746, 747], dtype='int64', name='index'),
 Int64Index([703, 704, 782], dtype='int64', name='index'),
 Int64Index([705], dtype='int64', name='index'),
 Int64Index([710, 711], dtype='int64', name='index'),
 Int64Index([728, 729, 730, 731], dtype='int64', name='index'),
 Int64Index([737, 738, 739], dtype='int64', name='index'),
 Int64Index([740, 741, 742, 743, 744], dtype='int64', name='index'),
 Int64Index([748, 749], dtype='int64', name='index'),
 Int64Index([763], dtype='int64', name='index'),
 Int64Index([764, 765], dtype='int64', name='index'),
 Int64Index([ 766,  767,  772,  773,  839,  840,  841, 1047, 1049, 1050, 1051,
             1052, 1053, 1054, 1055, 1056],
            dtype='int64', name='index'),
 Int64Index([768, 769, 770, 771], dtype='int64', name='index'),
 Int64Index([778, 779], dtype='int64', name='index'),
 Int64Index([780], dtype='int64', name='index'),
 Int64Index([783], dtype='int64', name='index'),
 Int64Index([784, 785, 786], dtype='int64', name='index'),
 Int64Index([787, 788, 789, 790, 791, 792, 793, 794, 795], dtype='int64', name='index'),
 Int64Index([799, 800, 801, 802, 803, 804], dtype='int64', name='index'),
 Int64Index([807, 808, 809, 810], dtype='int64', name='index'),
 Int64Index([811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821], dtype='int64', name='index'),
 Int64Index([822, 823, 824, 825, 826], dtype='int64', name='index'),
 Int64Index([827, 1319], dtype='int64', name='index'),
 Int64Index([828, 829, 1345], dtype='int64', name='index'),
 Int64Index([832], dtype='int64', name='index'),
 Int64Index([833, 834, 835], dtype='int64', name='index'),
 Int64Index([842, 1090], dtype='int64', name='index'),
 Int64Index([847], dtype='int64', name='index'),
 Int64Index([848, 849], dtype='int64', name='index'),
 Int64Index([860, 861, 1041, 1042, 1043, 1059, 1060, 1398, 1401], dtype='int64', name='index'),
 Int64Index([868, 869, 870, 871, 872, 873, 874, 875, 1403], dtype='int64', name='index'),
 Int64Index([890, 891, 892, 893, 1035, 1036, 1260, 1261, 1262], dtype='int64', name='index'),
 Int64Index([894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905], dtype='int64', name='index'),
 Int64Index([921, 922, 923, 924, 925], dtype='int64', name='index'),
 Int64Index([926, 927, 928, 929, 930, 931], dtype='int64', name='index'),
 Int64Index([932, 933, 934, 935, 936, 937], dtype='int64', name='index'),
 Int64Index([940, 941, 942, 943, 944, 945, 946], dtype='int64', name='index'),
 Int64Index([947, 948, 949], dtype='int64', name='index'),
 Int64Index([953, 954, 955], dtype='int64', name='index'),
 Int64Index([956, 957, 958], dtype='int64', name='index'),
 Int64Index([959, 960], dtype='int64', name='index'),
 Int64Index([961, 962, 963], dtype='int64', name='index'),
 Int64Index([964, 965, 966, 967], dtype='int64', name='index'),
 Int64Index([968, 969, 970], dtype='int64', name='index'),
 Int64Index([971, 972, 973, 974], dtype='int64', name='index'),
 Int64Index([975, 976, 977, 978], dtype='int64', name='index'),
 Int64Index([979, 980, 981, 982], dtype='int64', name='index'),
 Int64Index([983], dtype='int64', name='index'),
 Int64Index([984, 985], dtype='int64', name='index'),
 Int64Index([1008], dtype='int64', name='index'),
 Int64Index([1009, 1010, 1011], dtype='int64', name='index'),
 Int64Index([1012, 1013, 1014, 1015], dtype='int64', name='index'),
 Int64Index([1016, 1017, 1018], dtype='int64', name='index'),
 Int64Index([1019, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1399], dtype='int64', name='index'),
 Int64Index([1020], dtype='int64', name='index'),
 Int64Index([1021, 1022], dtype='int64', name='index'),
 Int64Index([1023, 1024, 1025, 1409], dtype='int64', name='index'),
 Int64Index([1026, 1027], dtype='int64', name='index'),
 Int64Index([1048], dtype='int64', name='index'),
 Int64Index([1058, 1414], dtype='int64', name='index'),
 Int64Index([1070, 1071, 1072, 1073, 1074, 1075, 1076, 1387], dtype='int64', name='index'),
 Int64Index([1088, 1089], dtype='int64', name='index'),
 Int64Index([1091], dtype='int64', name='index'),
 Int64Index([1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101], dtype='int64', name='index'),
 Int64Index([1121, 1122, 1123, 1124, 1433], dtype='int64', name='index'),
 Int64Index([1129, 1130, 1131, 1132], dtype='int64', name='index'),
 Int64Index([1136, 1137, 1138], dtype='int64', name='index'),
 Int64Index([1167], dtype='int64', name='index'),
 Int64Index([1169, 1170, 1171], dtype='int64', name='index'),
 Int64Index([1172], dtype='int64', name='index'),
 Int64Index([1173], dtype='int64', name='index'),
 Int64Index([1177], dtype='int64', name='index'),
 Int64Index([1192, 1193, 1194, 1323], dtype='int64', name='index'),
 Int64Index([1195], dtype='int64', name='index'),
 Int64Index([1196, 1197], dtype='int64', name='index'),
 Int64Index([1198], dtype='int64', name='index'),
 Int64Index([1199], dtype='int64', name='index'),
 Int64Index([1200, 1201, 1202], dtype='int64', name='index'),
 Int64Index([1203], dtype='int64', name='index'),
 Int64Index([1204, 1205], dtype='int64', name='index'),
 Int64Index([1206, 1207], dtype='int64', name='index'),
 Int64Index([1208], dtype='int64', name='index'),
 Int64Index([1211, 1212, 1213, 1214, 1215], dtype='int64', name='index'),
 Int64Index([1216, 1217], dtype='int64', name='index'),
 Int64Index([1220, 1221], dtype='int64', name='index'),
 Int64Index([1222, 1223, 1224], dtype='int64', name='index'),
 Int64Index([1225, 1226, 1227], dtype='int64', name='index'),
 Int64Index([1228], dtype='int64', name='index'),
 Int64Index([1229, 1290], dtype='int64', name='index'),
 Int64Index([1232], dtype='int64', name='index'),
 Int64Index([1233, 1255], dtype='int64', name='index'),
 Int64Index([1237, 1245], dtype='int64', name='index'),
 Int64Index([1238, 1239, 1291, 1292, 1293], dtype='int64', name='index'),
 Int64Index([1246, 1280, 1415, 1424, 1425], dtype='int64', name='index'),
 Int64Index([1247, 1248], dtype='int64', name='index'),
 Int64Index([1249, 1250], dtype='int64', name='index'),
 Int64Index([1263], dtype='int64', name='index'),
 Int64Index([1264], dtype='int64', name='index'),
 Int64Index([1265, 1277], dtype='int64', name='index'),
 Int64Index([1269, 1270], dtype='int64', name='index'),
 Int64Index([1271, 1272, 1285], dtype='int64', name='index'),
 Int64Index([1273], dtype='int64', name='index'),
 Int64Index([1274], dtype='int64', name='index'),
 Int64Index([1275], dtype='int64', name='index'),
 Int64Index([1276], dtype='int64', name='index'),
 Int64Index([1286], dtype='int64', name='index'),
 Int64Index([1306, 1307, 1308, 1309, 1310], dtype='int64', name='index'),
 Int64Index([1320], dtype='int64', name='index'),
 Int64Index([1321, 1322], dtype='int64', name='index'),
 Int64Index([1324], dtype='int64', name='index'),
 Int64Index([1327], dtype='int64', name='index'),
 Int64Index([1328], dtype='int64', name='index'),
 Int64Index([1329], dtype='int64', name='index'),
 Int64Index([1330], dtype='int64', name='index'),
 Int64Index([1331], dtype='int64', name='index'),
 Int64Index([1335], dtype='int64', name='index'),
 Int64Index([1336], dtype='int64', name='index'),
 Int64Index([1337, 1338], dtype='int64', name='index'),
 Int64Index([1339], dtype='int64', name='index'),
 Int64Index([1340], dtype='int64', name='index'),
 Int64Index([1341, 1342], dtype='int64', name='index'),
 Int64Index([1343, 1344], dtype='int64', name='index'),
 Int64Index([1350], dtype='int64', name='index'),
 Int64Index([1351], dtype='int64', name='index'),
 Int64Index([1352], dtype='int64', name='index'),
 Int64Index([1353], dtype='int64', name='index'),
 Int64Index([1354], dtype='int64', name='index'),
 Int64Index([1355], dtype='int64', name='index'),
 Int64Index([1356], dtype='int64', name='index'),
 Int64Index([1357], dtype='int64', name='index'),
 Int64Index([1358], dtype='int64', name='index'),
 Int64Index([1359], dtype='int64', name='index'),
 Int64Index([1360], dtype='int64', name='index'),
 Int64Index([1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368], dtype='int64', name='index'),
 Int64Index([1383], dtype='int64', name='index'),
 Int64Index([1384], dtype='int64', name='index'),
 Int64Index([1393, 1394], dtype='int64', name='index'),
 Int64Index([1396], dtype='int64', name='index'),
 Int64Index([1400], dtype='int64', name='index'),
 Int64Index([1404], dtype='int64', name='index'),
 Int64Index([1408], dtype='int64', name='index'),
 Int64Index([1411], dtype='int64', name='index'),
 Int64Index([1412], dtype='int64', name='index'),
 Int64Index([1416, 1417], dtype='int64', name='index'),
 Int64Index([1426, 1427], dtype='int64', name='index'),
 Int64Index([1429, 1430, 1432, 1434, 1435, 1437], dtype='int64', name='index'),
 Int64Index([1431, 1439, 1445], dtype='int64', name='index'),
 Int64Index([1436], dtype='int64', name='index'),
 Int64Index([1438], dtype='int64', name='index'),
 Int64Index([1440], dtype='int64', name='index'),
 Int64Index([1441], dtype='int64', name='index'),
 Int64Index([1444], dtype='int64', name='index')]

kl=[]
for i in  y:
    for j in i:
         if j==0:
            kl.append(j)
            print(j)
kl.to_string()

In [19]:
sam_cate_index=[]
value=31
for i in cate_group:
     if value in i:
            print(i)
            sam_cate_index=i

Int64Index([29, 30, 31, 1218, 1219], dtype='int64', name='index')

In [20]:
sam_cate_index

Int64Index([29, 30, 31, 1218, 1219], dtype='int64', name='index')

In [21]:
titles_name_based_on_same_cate=[]
for i in sam_cate_index:
    titles=data.iloc[i][['title']]
    #dl=dl.tolist()
    titles_name_based_on_same_cate.append(titles)
    print(titles)

title    I was rejected over 200 times before I landed ...
Name: 29, dtype: object
title    I was rejected over 200 times before I landed ...
Name: 30, dtype: object
title    I was rejected over 200 times before I landed ...
Name: 31, dtype: object
title    Sociology in India
Name: 1218, dtype: object
title    Sociology in India
Name: 1219, dtype: object

In [22]:
titles=pd.DataFrame(titles_name_based_on_same_cate)
titles=titles.title.tolist()
titles

['I was rejected over 200 times before I landed my first job',
 'I was rejected over 200 times before I landed my first job',
 'I was rejected over 200 times before I landed my first job',
 'Sociology in India',
 'Sociology in India']

## Titles are duplicate so i am using set 
## bcoz set not allowed duplicates values

In [23]:
titles=set(titles)
titles

{'I was rejected over 200 times before I landed my first job',
 'Sociology in India'}

In [24]:
data

,name,gender,academics,user_id,post_id,timestamp,title,category,post_type,main_cate,cate_1,cate_2,cate_3,cate_4,cate_5,cate_6
index,,,,,,,,,,,,,,,,
0,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed3820f76027d35905ccac8,2020-05-31T18:01:54.308Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
1,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed3820f76027d35905ccac8,2020-05-31T20:40:18.693Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
2,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
3,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed3820f76027d35905ccac8,2020-05-31T10:08:37.079Z,Configure Docker with Django; PostgreSQL; Pg-a...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None
4,Nivesh Singh Chauhan,male,undergraduate,5d60098a653a331687083238,5ed1ff0276027d35905cc60d,2020-05-31T08:21:29.911Z,AWS services and how to launch OS on AWS Cloud,Computer Technology|Cloud Computing,blog,Computer Technology,Cloud Computing,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5de179d80eb5e25a8a07f079,2020-05-30T10:26:47.432Z,Navigation system using BFS DFS algorithms,NaN,project,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,Kanika Sharma,female,undergraduate,5ecb979eeaff6b0c3a58a4f0,5ed175f476027d35905cc562,2020-05-29T20:53:54.008Z,GAN's Introduction,NaN,project,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1444,ashish,male,graduate,5ecf6e6576027d35905cbeec,5ed0007a76027d35905cc0ea,2020-05-29T09:00:06.934Z,A solar-powered microbrewery has design-led en...,Artistic design,artwork,Artistic design,None,None,None,None,None,None
1445,Asif Hossain,male,undergraduate,5ed0defa76027d35905cc2de,5ed23d4276027d35905cc798,2020-06-01T08:07:22.659Z,Energy.,Calligraphy|Typography|Pen and ink,artwork,Calligraphy,Typography,Pen and ink,None,None,None,None
1446,Parth Vijay,male,undergraduate,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology|Computer Application|Infor...,blog,Computer Technology,Computer Application,Information Technology,None,None,None,None

# please enter the user_id in user variable

In [25]:
user="5ed3748576027d35905ccaab"   # enter here user_id
#print(user)
df=(data[data['user_id']==user].index.values)
index_value_of_title=df[0]
#print(index_value_of_title)
dl=data.iloc[index_value_of_title][['category', 'user_id']]
user_id=dl.user_id
sam_cate_index=[]
value=index_value_of_title
for i in cate_group:
     if value in i:
            sam_cate_index=i
            
            
titles_name_based_on_same_cate=[]
for i in sam_cate_index:
    titles=data.iloc[i][['title']]
    titles_name_based_on_same_cate.append(titles)
    
titles=pd.DataFrame(titles_name_based_on_same_cate)
titles=titles.title.tolist()
titles=set(titles)
    
print(f"user_id : {user_id} \n->->->Recommanded Titles are->->->:")
count=0
for i in titles:
    print(count," ",i)
    count+=1

user_id : 5ed3748576027d35905ccaab
->->->Recommanded Titles are->->->:
0   Network & it's types
1   Configure Docker with Django; PostgreSQL; Pg-admin & Elasticsearch
2   Baseband & Broadband
3   Configure CI/CD Pipeline in GitLab and deployment to server via SSH
4   Decision Making with 7 steps !!!
5   Database management system(DBMS)
6   Network Model

# I am recommanded titles based on category column. I am only using idea and predict, not used the  properly machine learning in this project.

# this program predict titles based on same category